export const caUi = {
  appLanguage: "Idioma de l'aplicació",
  setup: "Configuració",
  template: "Plantilla",
  edit: "Editar",
  export: "Exportar",
  step: "Pas",
  of: "de",
  createCv: "Crea el teu CV",
  setupIntro: "Configura com vols començar.",
  chooseTemplate: "Tria una plantilla",
  templateIntro:
    "Tria l'estructura visual del teu CV. Podràs canviar els colors a l'editor.",
  originalTemplate: "Original",
  cvLanguage: "Idioma del CV",
  spanish: "Español",
  english: "English",
  catalan: "Català",
  howStart: "Com vols començar?",
  resume: "Continua amb el meu CV",
  resumeDetail: "Els últims canvis desats",
  sample: "Fes servir el CV d'exemple",
  sampleDetail: "Carrega un CV complet com a punt de partida",
  empty: "Comença des de zero",
  emptyDetail: "Crea una estructura buida i preparada per editar",
  importCv: "Importa un CV",
  importDetail: "Carrega un fitxer JSON exportat per l'aplicació",
  jsonExampleTitle: "Exemple de fitxer JSON",
  jsonExampleDetail:
    "Descarrega un fitxer vàlid amb el CV d'exemple per consultar-ne l'estructura o fer-lo servir com a plantilla.",
  downloadJsonExample: "Descarrega el JSON d'exemple",
  privacy: "Privacitat",
  privacyPolicy: "Política de privacitat",
  privacyNotice:
    "El teu CV es desa localment en aquest dispositiu i no n'emmagatzemem el contingut als nostres servidors.",
  learnMore: "Més informació",
  deleteLocalData: "Elimina les dades locals",
  deleteLocalDataTitle: "Vols eliminar les dades locals?",
  deleteLocalDataMessage:
    "Això eliminarà d'aquest navegador els CV i les preferències emmagatzemats per aquesta aplicació. Aquesta acció no es pot desfer.",
  cancel: "Cancel·la",
  delete: "Elimina",
  continueEditor: "Continua a l'editor →",
  continueTemplate: "Tria una plantilla →",
  editor: "Editor",
  preview: "Vista prèvia",
  editorViewLabel: "Vista de l'editor",
  back: "← Torna",
  next: "Següent →",
  reviewExport: "Revisa i exporta",
  reviewDetail:
    "Comprova el resultat final abans d'imprimir-lo o desar-ne les dades.",
  missingName: "El teu CV encara no té nom.",
  missingExperience: "No has afegit experiència.",
  backEdit: "← Torna a editar",
  exportData: "Exporta les dades (.json)",
  printPdf: "Descarrega / Imprimeix el PDF",
  style: "Colors / estil",
  helper:
    "Les dades es desen a localStorage. Per descarregar el PDF, fes servir el botó d'impressió i tria «Desa com a PDF».",
  addPage: "Afegeix una pàgina",
  deleteLastPage: "Elimina l'última pàgina",
  addSection: "Afegeix una secció personalitzada",
  resetSample: "Restableix amb l'exemple",
  personalData: "Dades personals",
  showPhoto: "Mostra la fotografia al CV",
  personPhoto: "Fotografia de la persona",
  addPhoto: "Afegeix una foto",
  changePhoto: "Canvia la foto",
  removePhoto: "Elimina",
  photoHelp: "PNG, JPG o WebP. Mida màxima: 1,5 MB.",
  photoInvalid: "Selecciona un fitxer d'imatge vàlid.",
  photoTooLarge: "La imatge supera la mida màxima d'1,5 MB.",
  photoReadError: "No s'ha pogut llegir la imatge.",
  name: "Nom",
  role: "Rol",
  commaTags: "Etiquetes separades per comes",
  phone: "Telèfon",
  sections: "Seccions",
  page: "Pàgina",
  column: "Columna",
  sidebar: "Barra lateral",
  main: "Principal",
  title: "Títol",
  deleteSection: "Elimina la secció",
  item: "Element",
  addItem: "Afegeix un element",
  deleteItem: "Elimina l'element",
  text: "Text",
  companyTitle: "Empresa / títol",
  positionSubtitle: "Càrrec / subtítol",
  dateLocation: "Data i ubicació",
  description: "Descripció",
  bullets: "Punts, un per línia",
  groupName: "Nom del grup",
  deleteGroup: "Elimina el grup",
  newTechnology: "Tecnologia nova",
  add: "Afegeix",
  addGroup: "Afegeix un grup",
  replaceCurrent:
    "Aquesta opció substituirà el contingut actual. Vols continuar?",
  resetConfirm:
    "Això substituirà el contingut actual pel CV d'exemple. Vols continuar?",
  readError: "No s'ha pogut llegir el fitxer.",
  invalidFile: "El fitxer no conté dades de CV vàlides.",
  unsupportedFile:
    "El fitxer fa servir una versió que aquesta aplicació encara no admet.",
  pageHasSections:
    "La pàgina {{page}} conté seccions. Si l'elimines, també se n'esborrarà el contingut. Vols continuar?",
};
